### PR TITLE
Add additional information to Undo and Sort commands in UG

### PR DESCRIPTION
**Pull request by lyuting47**

### CODE REVIEW

**Review by waynezsy — CHANGES_REQUESTED** [review]
Do you think it'll be better to have a table of the possible criterion?

Rather than describing everything in paragraph form.

**Comment by lyuting47** [comment]
> Do you think it'll be better to have a table of the possible criterion?
> 
> Rather than describing everything in paragraph form.

Hmm I feel like a table isn't really necessary since there are only 3 criteria? Maybe I can make a simple point form list?

**Review by waynezsy — APPROVED** [review]
LGTM

**Review by waynezsy — APPROVED** [review]
LGTM

**Pull request merged**
