### PR TITLE
Reorder UG features and summary table

### PR DESCRIPTION
**Pull request by WR3nd3**
Further reordering necessary.

### CODE REVIEW

**Review by waynezsy — APPROVED** [review]
~~I think need to explain how you split~~

See the review below requesting changes.

**Review by waynezsy — CHANGES_REQUESTED** [review]
I think you need to explain how these split tables are organised.

**Review by waynezsy — APPROVED** [review]
LGTM

**Review by lyuting47 — APPROVED** [review]
LGTM

**Pull request merged**
